<a href="https://colab.research.google.com/github/ferdinanIndra/Latihan_DAA_Pertemuan3/blob/main/LatihanDAA_Pertemuan03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [ ]:
import datetime as dt
tanggal = dt.date.today()
Mahasiswa = ['John', '2023071069', 'Informatika', 'DAA', tanggal, 'Universitas Pembangunan Jaya']
print(Mahasiswa)


['John', '2023071069', 'Informatika', 'DAA', datetime.date(2024, 9, 20), 'Universitas Pembangunan Jaya']


In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[0:2]

['Red', 'Green']

In [ ]:
print(bin_colors[1:2])

['Green']


In [ ]:
print(bin_colors[2:2])

[]


In [ ]:
print(bin_colors[1:3])

['Green', 'Blue']


In [ ]:
mahasiswa = ['John', '2023071069', 'Informatika', 'DAA', tanggal, 'Universitas Pembangunan Jaya']
print("Nim dan Prodi :", mahasiswa[1:3])


Nim dan Prodi : ['2023071069', 'Informatika']


In [ ]:
mahasiswa = ['John', '2023071069', 'Informatika', 'DAA', tanggal, 'Universitas Pembangunan Jaya']
print("tanggal dan  :", mahasiswa[1:3])

tanggal dan  : ['2023071069', 'Informatika']


In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
for aColor in bin_colors:
  print(aColor, " Square")

Red  Square
Green  Square
Blue  Square
Yellow  Square


In [ ]:
mahasiswa = ['John', '2023071069', 'Informatika', 'DAA', tanggal, 'Universitas Pembangunan Jaya']
for aMahasiswa in mahasiswa:
  print(aMahasiswa, " UPJ")


John  UPJ
2023071069  UPJ
Informatika  UPJ
DAA  UPJ
2024-09-20  UPJ
Universitas Pembangunan Jaya  UPJ


In [ ]:
namakampus = ['Universitas', 'Pembangunan', 'Jaya']
for aKampus in namakampus:
  print(aKampus)

Universitas
Pembangunan
Jaya


In [ ]:
#NESTED TUPLE
nested_tuple = ((100), (200, 400, 600), (300), (400, 800))
print(nested_tuple[0])
print(nested_tuple[1])
print(nested_tuple[2])
print(nested_tuple[3])

100
(200, 400, 600)
300
(400, 800)


In [ ]:
#DICTIONARY
mahasiswa={
    "nama": "Ferdinan Indra Fata",
    "nim": "2023071059",
    "prodi": "Informatika",
    "Universitas": "UPJ"
}

print(mahasiswa)

{'nama': 'Ferdinan Indra Fata', 'nim': '2023071059', 'prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
def pisahkan_warna(yellow_red):


  warna_kata = {'yellow': set(), 'red': set()}
  warna_dominan = {'yellow': {'dandelions', 'leaves'}, 'red': {'blood', 'rose', 'fire hydrant'}}

  for kata in kata_kata:
    for warna in warna_dominan:
      if kata in warna_dominan[warna]:
        warna_kata[warna].add(kata)

  return warna_kata

yellow_red = {'blood', 'rose', 'dandelions', 'fire hydrant', 'leaves'}
hasil = pisahkan_warna(yellow_red)
print(hasil)


{'yellow': {'dandelions', 'leaves'}, 'red': {'fire hydrant', 'blood', 'rose'}}


In [ ]:
import pandas as pd

data = [
    ["1", "Informatika", 50, 30, 20],
    ["2", "Sistem Informasi", 55, 30, 25],
    ["3", "Teknik Sipil", 40, 30, 10]
]

Prodi = pd.DataFrame(data, columns=["No", "Prodi", "Mahasiswa", "Laki-laki", "Perempuan"])

print(Prodi)

  No             Prodi  Mahasiswa  Laki-laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         25
2  3      Teknik Sipil         40         30         10


In [ ]:
import numpy as np
myMatrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(myMatrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [ ]:
import pandas as pd